package Formularios;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectoiventarios.Datos;

public class frmCliente extends javax.swing.JInternalFrame {

    Datos misDatos = new Datos();
    private DefaultTableModel miTabla; //Estructura la tabla//
    boolean modificar = false;

    public frmCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        txtcel = new javax.swing.JTextField();
        txtaddres = new javax.swing.JTextField();
        btnnew = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnchange = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Clientes");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("ID Cliente:");

        jLabel2.setText("Nombres(s):");

        jLabel3.setText("Apellido(s):");

        jLabel4.setText("Email:");

        jLabel5.setText("Telefono(s):");

        jLabel6.setText("Celular:");

        txtname.setEnabled(false);

        txtid.setEnabled(false);

        txttel.setEnabled(false);

        txtlastname.setEnabled(false);

        txtcel.setEnabled(false);

        txtaddres.setEnabled(false);

        btnnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevo.png"))); // NOI18N
        btnnew.setToolTipText("Nuevo  Cliente");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        btnsave.setToolTipText(" Guardar Cambios");
        btnsave.setEnabled(false);
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Eliminar.png"))); // NOI18N
        btndelete.setToolTipText("Eliminar");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar2.png"))); // NOI18N
        btncancel.setToolTipText("Cancelar");
        btncancel.setEnabled(false);
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.setEnabled(false);
        jScrollPane1.setViewportView(Tabla);

        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("Todos los campos son obligatorios...");

        btnchange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Editar.png"))); // NOI18N
        btnchange.setToolTipText("Nuevo  Cliente");
        btnchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtlastname, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                            .addComponent(txtname)
                                            .addComponent(txtid)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel7)))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnchange, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnnew, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtaddres, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtcel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txttel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))))
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtaddres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnnew, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnchange, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed

//::::::::PARA HABILITAR LOS CAMPOS DE TEXTO Y BOTENES CUANDO SE LE DA NUEVO:::::://

    txtid.setText("");
    txtname.setText("");
    txtlastname.setText("");
    txttel.setText("");
    txtcel.setText("");
    txtaddres.setText("");


    txtid.setEnabled(true);
    txtname.setEnabled(true);
    txtlastname.setEnabled(true);
    txttel.setEnabled(true);
    txtcel.setEnabled(true);
    txtaddres.setEnabled(true);



    btnsave.setEnabled(true);
    btncancel.setEnabled(true);
    modificar=false;
    
    
}//GEN-LAST:event_btnnewActionPerformed

private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed

    /////:::::  COMPROBAR CAMPOS :::::: //////

    if (txtid.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Por Favor digitar un ID Cliente");
        txtid.requestFocusInWindow();
        return;
    }
    if (!datoNum(txtid.getText())) {
        JOptionPane.showMessageDialog(null, "El ID Cliente no es de tipo numerico");
        txtid.setText("");
        txtid.requestFocusInWindow();
        return;
    }
    if (txtname.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Por Favor digitar un Nombre(s)");
        txtname.requestFocusInWindow();
        return;
    }
    if (txtlastname.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Por Favor digitar un Apellido(s)");
        txtlastname.requestFocusInWindow();
        return;
    }
    if (txttel.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Por Favor digitar un telefóno");
        txttel.requestFocusInWindow();
        return;
    }
    if (!datoNum(txttel.getText())) {
        JOptionPane.showMessageDialog(null, "El Telefono no es de tipo numerico");
        txttel.setText("");
        txttel.requestFocusInWindow();
        return;
    }

    if (txtcel.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Por Favor digitar un Celular");
        txtcel.requestFocusInWindow();
        return;
    }
    if (!datoNum(txtcel.getText())) {
        JOptionPane.showMessageDialog(null, "El Celular no es de tipo numerico");
        txtcel.setText("");
        txtcel.requestFocusInWindow();
        return;
    }
    if (txtaddres.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Por Favor digitar un e-mail");
        txtaddres.requestFocusInWindow();
        return;
    }


    if (txtname.getText().equals("NOREGISTRO")) {
        JOptionPane.showMessageDialog(null, "no se registrara el usuario con las siguientes siglas NOREGISTRO ");
        txtname.requestFocusInWindow();
        return;
    }

    ////::: EDITAR REGISTRO Y GENERAR REGISTRO:::://///
    
    if (modificar) {
        if (misDatos.EditarCliente(
                txtid.getText(),
                txtname.getText(),
                txtlastname.getText(),
                txttel.getText(),
                txtcel.getText(),
                txtaddres.getText())) {

            JOptionPane.showMessageDialog(null, "Se ha modificado exitosamente");
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo registrar. Intentelo nuevamente");
        }
    } else {
        if (misDatos.RegistroCliente(
                txtid.getText(),
                txtname.getText(),
                txtlastname.getText(),
                txttel.getText(),
                txtcel.getText(),
                txtaddres.getText())) {

            JOptionPane.showMessageDialog(null, "Registro del cliente correctamenre");
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo registrar el cliente");
            return;
        }

    }


    /////:::::LIMPIAR CAMPOS:::::://////

    txtid.setText("");
    txtname.setText("");
    txtlastname.setText("");
    txttel.setText("");
    txtcel.setText("");
    txtaddres.setText("");

    ///////:::::::::HABILITAR CAMPOS:::::::://///////

    txtid.setEnabled(false);
    txtname.setEnabled(false);
    txtlastname.setEnabled(false);
    txttel.setEnabled(false);
    txtcel.setEnabled(false);
    txtaddres.setEnabled(false);
    ///::::HABILITACION DE BOTONES:::://///
    btnsave.setEnabled(false);
    btncancel.setEnabled(false);

    llenandoTabla();

}//GEN-LAST:event_btnsaveActionPerformed

private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed

    /////:::::LIMPIAR CAMPOS:::::://////

    txtid.setText("");
    txtname.setText("");
    txtlastname.setText("");
    txttel.setText("");
    txtcel.setText("");
    txtaddres.setText("");

    ///////:::::::::HABILITAR CAMPOS:::::::://///////

    txtid.setEnabled(false);
    txtname.setEnabled(false);
    txtlastname.setEnabled(false);
    txttel.setEnabled(false);
    txtcel.setEnabled(false);
    txtaddres.setEnabled(false);

    ///::::HABILITACION DE BOTONES:::://///
    btnsave.setEnabled(false);
    btncancel.setEnabled(false);






}//GEN-LAST:event_btncancelActionPerformed

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated

    llenandoTabla();
}//GEN-LAST:event_formInternalFrameActivated

private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed

    String DeleteClient = JOptionPane.showInputDialog("Ingrese ID del Cliente a eliminar.");

    if (DeleteClient.equals("")) {
        return;
    }

    if (misDatos.DeleteClient(DeleteClient)) {
        JOptionPane.showMessageDialog(null, "Cliente Eliminado correctamente");
    } else {
        JOptionPane.showMessageDialog(null, "No se encontro el usuario");
    }

    llenandoTabla();

}//GEN-LAST:event_btndeleteActionPerformed

    private void btnchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangeActionPerformed

        String change = JOptionPane.showInputDialog(null, "Digitar el ID del Usuario a modificar... =) ");

        if(change.equals("")){
            return;
        }
        
        try {
            ResultSet Datos = misDatos.tblCliente();

            while (Datos.next()) {

                if (Datos.getString("ID_Cliente").equals(change)) {

                    txtid.setText(Datos.getString("ID_Cliente"));
                    txtname.setText(Datos.getString("Nombre"));
                    txtlastname.setText(Datos.getString("Apellido"));
                    txttel.setText(Datos.getString("Telefono"));
                    txtcel.setText(Datos.getString("Celular"));
                    txtaddres.setText(Datos.getString("e_mail"));

                }
            }

        } catch (Exception e) {
            System.out.println("Error de consulta de datos" + e);
        }


        // ::::::::: ACTIVAR CAMPOS  :::::::::: //

        txtid.setEnabled(true);
        txtname.setEnabled(true);
        txtlastname.setEnabled(true);
        txttel.setEnabled(true);
        txtcel.setEnabled(true);
        txtaddres.setEnabled(true);

        ///:::::::::HABILITAR BOTONES::::::////


        btnsave.setEnabled(true);
        btncancel.setEnabled(true);

       modificar=true;





    }//GEN-LAST:event_btnchangeActionPerformed

    private void llenandoTabla() {

        try {

            String titulos[] = {"ID Cliente", "Nombre", "Apellido", "Telefono", "Celular", "Email"}; // crear los titulos
            String Regisgtros[] = new String[6];

            miTabla = new DefaultTableModel(null, titulos); // agrega los titulos a la tabla

            ResultSet rs = misDatos.tblCliente();
            while (rs.next()) {

                Regisgtros[0] = rs.getString("ID_Cliente");
                Regisgtros[1] = rs.getString("Nombre");
                Regisgtros[2] = rs.getString("Apellido");
                Regisgtros[3] = rs.getString("Telefono");
                Regisgtros[4] = rs.getString("Celular");
                Regisgtros[5] = rs.getString("e_mail");
                miTabla.addRow(Regisgtros);

            }
            Tabla.setModel(miTabla);
        } catch (Exception e) {
            System.out.println("Error busqueda de datos tabla de Clientes " + e);
        }

    }

    private boolean datoNum(String num) {

        try {
            Long numero = Long.parseLong(num);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnchange;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtaddres;
    private javax.swing.JTextField txtcel;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
