
package Formularios;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import proyectoiventarios.Datos;


public class frmReportes extends javax.swing.JInternalFrame {


    Datos misDatos = new Datos();
    DefaultTableModel miModelo;
    
    public frmReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Aceptar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reporte Contable");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tabla.setEnabled(false);
        jScrollPane1.setViewportView(Tabla);

        Aceptar.setText("ventas");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        jButton1.setText("Usuarios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clientes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Productos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ReponteCont.png"))); // NOI18N

        jButton4.setText("Pedidos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Aceptar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Aceptar)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3)
                        .addComponent(jButton4))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        
        
        Tabla.setVisible(false);
        
    }//GEN-LAST:event_formInternalFrameActivated

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
      
              try {

            String Titulos[] = {"ID Venta", "ID Usuario", "ID Cliente", "ID Producto", "Cantidad","Fecha"};
            String Registros[] = new String[6];

            miModelo = new DefaultTableModel(null, Titulos);

            ResultSet rs = misDatos.tblVentas();
            while (rs.next()) {

                    Registros[0] = rs.getString("ID_Venta");
                    Registros[1] = rs.getString("ID_Usuario");
                    Registros[2] = rs.getString("ID_Cliente");
                    Registros[3] = rs.getString("ID_Producto");
                    Registros[4] = rs.getString("CantidadP");
                    Registros[5] = rs.getString("Fecha");
                    miModelo.addRow(Registros);
                
            }

            Tabla.setModel(miModelo);

        } catch (Exception x) {
            System.out.println("Error al llenado de tabla " + x);
        }  
 
        Tabla.setVisible(true);
    }//GEN-LAST:event_AceptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
                try {
            String titulos[] = {"ID Usuario", "Nombre", "Apellido", "Perfil"};
            String Regisgtros[] = new String[4];
            miModelo = new DefaultTableModel(null, titulos);

            ResultSet rs = misDatos.tblUser();
            while (rs.next()) {

                Regisgtros[0] = rs.getString("ID_Usuario");
                Regisgtros[1] = rs.getString("Nombre");
                Regisgtros[2] = rs.getString("Apellido");
                Regisgtros[3] = misDatos.ConsPerfil(rs.getString("Nombre"));
                miModelo.addRow(Regisgtros);

            }
            Tabla.setModel(miModelo);
            
        } catch (Exception e) {
            System.out.println("Error busqueda de datos tabla usuarios " + e);
        }
        
        Tabla.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
             
        try{
            
            String Titulos[] = {"ID Producto","Nombre","Categoria","Precio","Cantidad"};
            String Registros[]= new String[5];
            
            miModelo = new DefaultTableModel(null, Titulos);
            
            ResultSet rs = misDatos.tblProducto();
            while(rs.next()){
                Registros[0] = rs.getString("ID_Producto");
                Registros[1] = rs.getString("Nombre");
                Registros[2] = rs.getString("Categoria");
                Registros[3] = rs.getString("PrecioU");
                Registros[4] = rs.getString("Cantidad");
                miModelo.addRow(Registros);
            }
            
            Tabla.setModel(miModelo);
            Tabla.getColumnModel().getColumn(1).setPreferredWidth(150);
            
        }catch(Exception x){
            System.out.println("Error al llenado de tabla "+x);
        }
              
        Tabla.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
          try {

            String titulos[] = {"ID Cliente", "Nombre", "Apellido", "Telefono", "Celular", "Email"}; // crear los titulos
            String Regisgtros[] = new String[6];

            miModelo = new DefaultTableModel(null, titulos); // agrega los titulos a la tabla

            ResultSet rs = misDatos.tblCliente();
            while (rs.next()) {

                Regisgtros[0] = rs.getString("ID_Cliente");
                Regisgtros[1] = rs.getString("Nombre");
                Regisgtros[2] = rs.getString("Apellido");
                Regisgtros[3] = rs.getString("Telefono");
                Regisgtros[4] = rs.getString("Celular");
                Regisgtros[5] = rs.getString("e_mail");
                miModelo.addRow(Regisgtros);

            }
            Tabla.setModel(miModelo);
        } catch (Exception e) {
            System.out.println("Error busqueda de datos tabla de Clientes " + e);
        }
        
        Tabla.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
               try{
            
            String Titulos[] = {"ID Pedido","ID Producto","ID Proveedor","Numero de Pedidos"};
            String Registros[]= new String[4];
            
            miModelo = new DefaultTableModel(null, Titulos);
            
            ResultSet rs = misDatos.ConsPedidos();
            while(rs.next()){
                Registros[0] = rs.getString("ID_Pedido");
                Registros[1] = rs.getString("ID_Producto");
                Registros[2] = rs.getString("ID_Proveedor");
                Registros[3] = rs.getString("NumPedidos");
              
                miModelo.addRow(Registros);
            }
            
            Tabla.setModel(miModelo);
            
        }catch(Exception x){
            System.out.println("Error al llenado de tabla "+x);
        }
              
        Tabla.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
